on:
  workflow_dispatch:
    inputs:
        version:
          description: Bump Version
          default: v1.0.0
          required: true
        eco_version:
          description: Eco Version
          default: v0.9.7.12
          required: true
          
name: Create Release

jobs:
  build:
    name: Package and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package code
        run: |
          cp -r "./XP Benefits/src" "./package"
          sed -i "1s/.*/# XP Benefits ${{ github.event.inputs.version }} for Eco ${{ github.event.inputs.eco_version}}/" "./package/Mods/UserCode/XP Benefits/README.md"
          cp "LICENSE" "./package/Mods/UserCode/XP Benefits/LICENSE"
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip Contents
        run: |
          cd package
          zip -qq -r "XP-Benefits-${{ github.event.inputs.version }}.zip" Mods
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1        
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          body: "XP Benefits ${{ github.event.inputs.version }} for Eco ${{ github.event.inputs.eco_version}}"
          artifacts: "package/XP-Benefits-${{ github.event.inputs.version }}.zip"
          allowUpdates: true
